// Package detector — monitor.go (Phase 06: with alerting integration)
//
// The monitoring loop that ties together data fetching, statistical analysis,
// drift detection, and alerting. Runs on a configurable interval, fetching
// recent predictions from the serving API, comparing their feature distributions
// against the training reference, and sending webhook alerts when drift exceeds
// the configured threshold.
//
// Architecture:
//   Serving API ──(HTTP)──▶ Monitor ──(stats)──▶ DriftResult[] ──▶ Alerting
package detector

import (
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"time"

	"github.com/ethan-k-francis/ml-production-pipeline/drift-detector/internal/alerting"
)

// ReferenceDistributions maps feature names to their training distributions.
// Loaded once at startup from the JSON file produced by the training pipeline.
type ReferenceDistributions map[string]FeatureDistribution

// Monitor coordinates periodic drift checks against the serving API.
type Monitor struct {
	servingURL     string
	checkInterval  time.Duration
	driftThreshold float64
	windowSize     int
	reference      ReferenceDistributions
	webhook        *alerting.WebhookClient
	logger         *slog.Logger
}

// NewMonitor creates a drift monitor with the given configuration.
// The webhookURL can be empty to disable alerting (alerts are just logged).
func NewMonitor(
	servingURL string,
	checkInterval time.Duration,
	driftThreshold float64,
	windowSize int,
	reference ReferenceDistributions,
	webhookURL string,
) *Monitor {
	return &Monitor{
		servingURL:     servingURL,
		checkInterval:  checkInterval,
		driftThreshold: driftThreshold,
		windowSize:     windowSize,
		reference:      reference,
		webhook:        alerting.NewWebhookClient(webhookURL),
		logger:         slog.New(slog.NewJSONHandler(os.Stdout, nil)),
	}
}

// LoadReference reads reference distributions from a JSON file.
// This file is generated by training/train.py after model training.
func LoadReference(path string) (ReferenceDistributions, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading reference distributions: %w", err)
	}

	var ref ReferenceDistributions
	if err := json.Unmarshal(data, &ref); err != nil {
		return nil, fmt.Errorf("parsing reference distributions: %w", err)
	}

	return ref, nil
}

// predictionEntry represents a single logged prediction from the serving API.
type predictionEntry struct {
	Timestamp   float64            `json:"timestamp"`
	Features    map[string]float64 `json:"features"`
	Prediction  int                `json:"prediction"`
	Probability float64            `json:"probability"`
}

// fetchPredictions retrieves recent prediction logs from the serving API.
func (m *Monitor) fetchPredictions() ([]predictionEntry, error) {
	url := fmt.Sprintf("%s/health", m.servingURL)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("fetching from serving API: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("serving API returned %d: %s", resp.StatusCode, string(body))
	}

	// For demonstration, generate synthetic current-window data.
	// Production would read from Redis streams or a prediction log API.
	return m.generateCurrentWindow(), nil
}

// generateCurrentWindow creates synthetic current-window data for drift analysis.
func (m *Monitor) generateCurrentWindow() []predictionEntry {
	entries := make([]predictionEntry, 0, m.windowSize)
	now := float64(time.Now().Unix())

	for i := 0; i < m.windowSize; i++ {
		features := make(map[string]float64)
		for name, dist := range m.reference {
			offset := float64(i) / float64(m.windowSize)
			features[name] = dist.Mean + (offset-0.5)*dist.Std*2
		}

		entries = append(entries, predictionEntry{
			Timestamp:   now - float64(m.windowSize-i),
			Features:    features,
			Prediction:  0,
			Probability: 0.1,
		})
	}

	return entries
}

// CheckDrift analyzes recent predictions against reference distributions.
// Returns a DriftResult for each feature with PSI, KS, and KL statistics.
func (m *Monitor) CheckDrift(predictions []predictionEntry) []DriftResult {
	results := make([]DriftResult, 0, len(m.reference))

	for featureName, refDist := range m.reference {
		currentValues := make([]float64, 0, len(predictions))
		for _, p := range predictions {
			if val, ok := p.Features[featureName]; ok {
				currentValues = append(currentValues, val)
			}
		}

		if len(currentValues) == 0 {
			continue
		}

		currentHist := Histogramize(currentValues, refDist.Histogram.BinEdges)

		psi := PSI(refDist.Histogram.Counts, currentHist)
		ks := KSStatistic(generateRefSamples(refDist, len(currentValues)), currentValues)
		kl := KLDivergence(currentHist, refDist.Histogram.Counts)

		currMean := mean(currentValues)
		severity := ClassifySeverity(psi)

		result := DriftResult{
			Feature:   featureName,
			PSI:       psi,
			KS:        ks,
			KL:        kl,
			IsDrifted: psi > m.driftThreshold,
			Severity:  severity,
			RefMean:   refDist.Mean,
			CurrMean:  currMean,
			MeanShift: currMean - refDist.Mean,
		}

		results = append(results, result)
	}

	return results
}

// generateRefSamples creates synthetic samples from a reference distribution.
func generateRefSamples(dist FeatureDistribution, n int) []float64 {
	samples := make([]float64, n)
	for i := 0; i < n; i++ {
		t := float64(i) / float64(n)
		samples[i] = dist.Min + t*(dist.Max-dist.Min)
	}
	return samples
}

// Run starts the monitoring loop. Blocks until the process is killed.
func (m *Monitor) Run() {
	m.logger.Info("drift monitor started",
		"serving_url", m.servingURL,
		"check_interval", m.checkInterval.String(),
		"drift_threshold", m.driftThreshold,
		"window_size", m.windowSize,
		"features_monitored", len(m.reference),
		"alerting_enabled", m.webhook != nil,
	)

	m.runCheck()

	ticker := time.NewTicker(m.checkInterval)
	defer ticker.Stop()

	for range ticker.C {
		m.runCheck()
	}
}

// runCheck performs a single drift check cycle.
// If drift is detected and a webhook is configured, sends an alert.
func (m *Monitor) runCheck() {
	m.logger.Info("running drift check")

	predictions, err := m.fetchPredictions()
	if err != nil {
		m.logger.Error("failed to fetch predictions", "error", err.Error())
		return
	}

	if len(predictions) == 0 {
		m.logger.Warn("no predictions to analyze")
		return
	}

	results := m.CheckDrift(predictions)

	// Collect drifted features for alerting
	var driftedAlerts []alerting.DriftAlert
	driftCount := 0

	for _, r := range results {
		if r.IsDrifted {
			driftCount++
			m.logger.Warn("drift detected",
				"feature", r.Feature,
				"psi", fmt.Sprintf("%.4f", r.PSI),
				"ks", fmt.Sprintf("%.4f", r.KS),
				"severity", r.Severity,
				"mean_shift", fmt.Sprintf("%.4f", r.MeanShift),
			)

			// Build alert for this drifted feature
			alert := alerting.NewDriftAlert(
				r.Feature,
				r.PSI, r.KS, r.KL,
				m.driftThreshold,
				r.MeanShift, r.RefMean, r.CurrMean,
				r.Severity,
			)
			driftedAlerts = append(driftedAlerts, alert)
		} else {
			m.logger.Info("feature stable",
				"feature", r.Feature,
				"psi", fmt.Sprintf("%.4f", r.PSI),
			)
		}
	}

	m.logger.Info("drift check complete",
		"total_features", len(results),
		"drifted_features", driftCount,
	)

	// Send webhook alert if any features drifted and alerting is configured
	if len(driftedAlerts) > 0 && m.webhook != nil {
		summary := alerting.NewAlertSummary(driftedAlerts, len(results))
		m.webhook.SendAlert(summary)
	}
}
